version: '3.8'

services:
  brp-backend:
#    image: mojaloop/beneficiary-registration-portal-backend:${BRP_BACKEND_IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env.example
    environment:
      - HOST=mysql
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my_network

  brp-frontend:
    build:
      context: ../beneficiary-registration-portal-frontend
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    env_file: .env.example
    restart: always
    networks:
      - my_network

  bms:
    build:
      context: ../beneficiary-management-system-svc
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    env_file: .env.example
    restart: always
    networks:
      - my_network


  mysql:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    volumes:
      # Note: this fixes the permissions issue, but docker-compose up will fail on first attempt
      - ./docker/sql-init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_USER=${USER:-user}
      - MYSQL_PASSWORD=${PASSWORD:-pass123}
      - MYSQL_DATABASE=${DATABASE:-brp}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "mysql" ]
      timeout: 10s
      retries: 5
      start_period: 30s
      interval: 10s


networks:
  my_network:
    driver: bridge
